# Generated by Django 3.0.5 on 2022-02-05 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
