# Generated by Django 3.0.5 on 2022-02-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='fee',
        ),
        migrations.AddField(
            model_name='studentextra',
            name='bmi',
            field=models.FloatField(null=True),
        ),
    ]
